# Generated by Django 4.2.9 on 2024-03-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
