# Generated by Django 4.2.5 on 2023-10-27 01:44

import cartpol_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='round',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='political',
            name='region',
            field=models.CharField(default='city', max_length=50, validators=[cartpol_app.models.validate_list]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='political',
            name='region_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
