# Generated by Django 4.2.9 on 2024-07-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0002_alter_neighborhood_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='political',
            name='political_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
