# Generated by Django 4.2.9 on 2024-01-13 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0002_election_code_election_round_political_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electoralzone',
            name='address',
        ),
        migrations.RemoveField(
            model_name='electoralzone',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='electoralzone',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='zone',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40)),
                ('cep', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=100)),
                ('electroal_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartpol_app.electoralzone')),
            ],
        ),
        migrations.AddField(
            model_name='votes',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cartpol_app.section'),
            preserve_default=False,
        ),
    ]
