# Generated by Django 4.2.9 on 2024-01-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0003_remove_electoralzone_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='electroal_zone',
            new_name='electoral_zone',
        ),
        migrations.AddField(
            model_name='electoralzone',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cartpol_app.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cartpol_app.neighborhood'),
            preserve_default=False,
        ),
    ]
