# Generated by Django 5.0.6 on 2024-07-15 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0003_political_political_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electoralzone',
            name='state',
        ),
        migrations.AddField(
            model_name='electoralzone',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cartpol_app.county'),
            preserve_default=False,
        ),
    ]
