# Generated by Django 5.0.6 on 2024-07-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0004_remove_electoralzone_state_electoralzone_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='tse_id',
            field=models.IntegerField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
