# Generated by Django 5.0.6 on 2024-08-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0005_county_tse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='subdistrito',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='map_neighborhood',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='county',
            name='tse_id',
            field=models.IntegerField(),
        ),
    ]
