# Generated by Django 5.0.6 on 2024-08-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0006_neighborhood_subdistrito_section_map_neighborhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='subdistrito',
        ),
        migrations.AddField(
            model_name='politicaltype',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cartpol_app.election'),
            preserve_default=False,
        ),
    ]
