# Generated by Django 5.0.6 on 2024-09-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0007_remove_neighborhood_subdistrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
