# Generated by Django 5.0.6 on 2024-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0008_section_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='year',
        ),
        migrations.AddField(
            model_name='electoralzone',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
