# Generated by Django 5.0.6 on 2024-09-18 15:24

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0009_remove_section_year_electoralzone_year'),
    ]

    operations = [
        UnaccentExtension()
    ]
