# Generated by Django 5.0.6 on 2024-10-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0010_auto_20240918_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='map_neighborhood',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='map_neighborhood',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
