# Generated by Django 5.0.6 on 2024-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0012_votes_cartpol_app_politic_5cdd0a_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='votes',
            name='cartpol_app_politic_5cdd0a_idx',
        ),
        migrations.AddIndex(
            model_name='votes',
            index=models.Index(fields=['political_id', 'section_id'], name='cartpol_app_politic_72603f_idx'),
        ),
    ]
