# Generated by Django 5.0.6 on 2024-11-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0013_remove_votes_cartpol_app_politic_5cdd0a_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='political',
            index=models.Index(fields=['political_type_id', 'region_id', 'election_id'], name='cartpol_app_politic_216c15_idx'),
        ),
    ]
