# Generated by Django 5.0.6 on 2025-04-24 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartpol_app', '0014_political_cartpol_app_politic_216c15_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotesInNeighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='political',
            name='cartpol_app_politic_216c15_idx',
        ),
        migrations.RemoveIndex(
            model_name='votes',
            name='cartpol_app_politic_72603f_idx',
        ),
        migrations.AddField(
            model_name='votesinneighborhood',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartpol_app.neighborhood'),
        ),
        migrations.AddField(
            model_name='votesinneighborhood',
            name='political',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartpol_app.political'),
        ),
    ]
